<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link http://book.cakephp.org/3.0/en/controllers.html#the-app-controller
 */
class TestController extends AppController {
    public function beforeFilter(Event $event)
    {
//        $this->Files = TableRegistry::get('Files');
        $this->loadModel('Files');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function test(){
        $tmp = $this->Files->find('all', array(
            'limit' => 10
        ))->toArray();
        $this->set('data', $tmp);
        print_r($tmp);
        exit();
    }
}
